env:
  global:
  - NODE_VERSION=stable

language: node_js
node_js: lts/*
before_install:
  - npm install -g npm@latest
  - npm install
  - npm install -g expo-cli

script:
  - npm ci
  - expo signin -u "indrareactnative" -p "qawsedrf12345"
  - expo start
//  - npx expo publish --non-interactive
//  - make test