env:
  global:
  - NODE_VERSION=stable

language: node_js
node_js: lts/*
before_install:
  - npm install -g npm@latest
  - npm install
  - npm install --save-dev expo-cli
  - yarn add expo

script:
  - npm ci
  - expo signin -u "indrareactnative" -p "qawsedrf12345"
  - expo start