version: '3'

services:
  indra-container-service:
    build: ./docker
    volumes:
      - .:/home/IndrasNet
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"